config/routes.rb
BMRNG::Application.routes.draw do

  get '/blog', to: redirect("http://google.com")

  resources :answers

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :questions

  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
    put 'update', :to => 'registrations#update'
    get 'account', :to => 'registrations#edit'
  end

  resources :users do
    resources :subscriptions
    match :send_feedback, via: [:get, :post]
    match :request_support, via: [:get, :post]
    member do
      get :analytics
      get :manage
      get :update_view
      match :change, via: [:get, :post, :patch]
      match :welcome, via: [:get]
      match :set_human_name, via: [:patch, :post]
      match :set_studio, via: [:get, :post]
      match :set_studio_url, via: [:get, :post]
      match :set_url, via: [:get, :post]
      match :set_logo, via: [:get, :post]
      match :set_questions, via: [:get, :post]
      match :welcome_complete, via: [:get]
      match :edit_subscription, via: [:get]
    end
  end

  resources :guests do
    collection do
      get :destroy_session
      get :start_session
      get :load
      get :save
      match :ask_questions, via: [:get, :post]
      get :thank_you
    end
  end

  resources :albums do
    member do
      match :display, via: [:get, :post]
      match :set_title, via: [:get, :post, :patch]
      match :set_password, via: [:get, :patch]
      match :settings, via: [:get, :post, :patch]
    end
    resources :photos do
      member do
        get :display
      end
    end
  end
    
  resources :photos do
    member do
      get :fave
      get :defave
    end
  end

  mount StripeEvent::Engine => '/stripe'

  get "home/update_view"

  get "photos/update_view"

  get "/feedback", to: 'questions#index'

  get '/admin/become' => 'admin#become'

  #constraints DomainConstraint.new ['myalbumviewer.dev', 'myalbumviewer.com'] do
  #  root to: 'home#viewer', as: :viewer
  #  resources :users, path: '/' do
  #    get '/:album_id' => 'albums#display'
  #  end
  #end

  constraints SubdomainConstraint.new ['cp'] do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  constraints SubdomainConstraint.new ['www'] do
    root to: 'home#index', as: :home
    resources :users, path: '/' do
      match '/:album_id' => 'albums#display', via: [:get, :post]
    end
  end

  root to: 'home#index', as: :default
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :guest
  belongs_to :question

  attr_accessible :guest, :question, :content
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json

  before_filter :authenticate_user!, :except => [:new, :create]

  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for(@answer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :question_id %>
    <%= f.input :content %>
    <%= f.input :guest_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Content</th>
    <th>Guest</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= answer.question_id %></td>
    <td><%= answer.content %></td>
    <td><%= answer.guest_id %></td>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Question:</b>
  <%= @answer.question_id %>
</p>

<p>
  <b>Content:</b>
  <%= @answer.content %>
</p>

<p>
  <b>Guest:</b>
  <%= @answer.guest_id %>
</p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>