config/routes.rb
BMRNG::Application.routes.draw do

  get '/blog', to: redirect("http://google.com")

  resources :answers

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :questions

  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
    put 'update', :to => 'registrations#update'
    get 'account', :to => 'registrations#edit'
  end

  resources :users do
    resources :subscriptions
    match :send_feedback, via: [:get, :post]
    match :request_support, via: [:get, :post]
    member do
      get :analytics
      get :manage
      get :update_view
      match :change, via: [:get, :post, :patch]
      match :welcome, via: [:get]
      match :set_human_name, via: [:patch, :post]
      match :set_studio, via: [:get, :post]
      match :set_studio_url, via: [:get, :post]
      match :set_url, via: [:get, :post]
      match :set_logo, via: [:get, :post]
      match :set_questions, via: [:get, :post]
      match :welcome_complete, via: [:get]
      match :edit_subscription, via: [:get]
    end
  end

  resources :guests do
    collection do
      get :destroy_session
      get :start_session
      get :load
      get :save
      match :ask_questions, via: [:get, :post]
      get :thank_you
    end
  end

  resources :albums do
    member do
      match :display, via: [:get, :post]
      match :set_title, via: [:get, :post, :patch]
      match :set_password, via: [:get, :patch]
      match :settings, via: [:get, :post, :patch]
    end
    resources :photos do
      member do
        get :display
      end
    end
  end
    
  resources :photos do
    member do
      get :fave
      get :defave
    end
  end

  mount StripeEvent::Engine => '/stripe'

  get "home/update_view"

  get "photos/update_view"

  get "/feedback", to: 'questions#index'

  get '/admin/become' => 'admin#become'

  #constraints DomainConstraint.new ['myalbumviewer.dev', 'myalbumviewer.com'] do
  #  root to: 'home#viewer', as: :viewer
  #  resources :users, path: '/' do
  #    get '/:album_id' => 'albums#display'
  #  end
  #end

  constraints SubdomainConstraint.new ['cp'] do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  constraints SubdomainConstraint.new ['www'] do
    root to: 'home#index', as: :home
    resources :users, path: '/' do
      match '/:album_id' => 'albums#display', via: [:get, :post]
    end
  end

  root to: 'home#index', as: :default
end

app/models/album.rb
class Album < ActiveRecord::Base
  is_impressionable counter_cache: true
  accepts_nested_attributes_for :impressions

## ========================== ATTRIBUTES ACCESSIBLE ==============================

  attr_accessible :user_id, :title, :session_image, :name, :watermark, 
                  :password_toggle, :password, :social

## ================================ CALLBACKS ====================================
  before_save :ensure_url_save_name

## =============================== VALIDATIONS ===================================

  validates_length_of :name, in: 1..50, allow_nil: false,  if: :name_changed?
  validates_length_of :title, in: 1..50, allow_nil: false, if: :title_changed?

## ================================ RELATIONS ====================================
  has_many :photos
  has_many :guests

  belongs_to :user

## ================================= SCOPES ====================================
  scope :active, -> {where(status: :active) }

  # utility to make finding things easier when the key could be an
  # object, integer, symbol, or string.   Works even if the string holds
  # an integer, so it can take params[:id] like "25020"
  def self.find_by_name_or_id(x)
    if x.is_a?(ActiveRecord::Base)
      r = x
    elsif x.is_a?(Fixnum)
      r = find_by_id(x)
    elsif x.is_a?(String) or x.is_a?(Symbol)
      if (r = find_by_name(x.to_s))
        r
      elsif !(x.is_a?(Symbol)) and ((i = x.to_i) and (i.to_s == x.to_s.strip))
        find_by_id(i)
      else
        nil
      end
    end
  end

  #REVIEW: THIS IS NOT DYNAMIC AT ALL
  def url
    "http://#{ENV['DISPLAY_SUBDOMAIN']}.boomerangproof.com/#{user.url_name}/#{name}"
  end

  def top_photos
    #MAJOR HACK!!! BAD PERF!!! THIS SHOULD BE A SCOPE
    photos.map{|p| p.followers_count > 0 ? [p.id, p.followers.count] : nil}.
           compact.sort_by{|p| -p[1]}[0..4].map{|p| Photo.find p[0]}
  end

  private

  def ensure_url_save_name
    self.name = name.gsub(' ', '_')
  end



end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  # authenticate users
  before_filter :authenticate_user!, :except => [:display]

  # gather page impressions
  #impressionist actions: [:display]

  def resource
    param = params['album_id'] || params['id']
    @user ||= Album.find_by_name_or_id(param)
  end
  
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @albums }
    end
  end

  def show
    @album = Album.find(params[:id])
    @photos = @album.photos
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  def display
    if @user = User.find_by_name_or_id(params[:user_id])
      if @album = @user.albums.active.where(name: params[:album_id].gsub(' ', '')).first
        impressionist(@album)
      end
    end
    raise ActiveRecord::RecordNotFound unless @album
    unless current_guest
      #verify password if necessary
      if request.get? and @album.password_toggle
        render :sign_in and return
      elsif request.post?
        unless @album.password == params[:album][:password]
          render :not_authorized and return
        end
      end
      #create session
      session[:guest_id] = Guest.create.id
    end

    @photos = if params[:faves] == "true"
      current_guest.all_following.map{|p| @album.photos.include?(p) ? p : nil}.flatten
    else
      @album.photos
    end
  end

  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  def create
    #fix the name up to not have spaces
    name = params[:album].delete(:name)
    name = name.gsub(' ', '')
    @album = Album.new(params[:album].merge(name: name))
    @album.status = 'created'

    respond_to do |format|
      if @album.save
        format.html { redirect_to set_title_album_path(@album) }
        format.json { render json: album_path(@album), status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_title
    if request.patch? or request.post?
      resource.title = params[:album][:title]
      if resource.valid?
        resource.save
        if resource.status == 'created'
          redirect_to set_password_album_path
        else
          redirect_to resource.user
        end
      end
    else
      @album = resource
    end
  end

  def set_password
    if request.patch?
      if params[:album][:password_toggle] == '1'
        resource.password_toggle = 1
        resource.password = params[:album][:password]
        if resource.save
          if resource.status == 'created'
            redirect_to settings_album_path and return
          else
            redirect_to resource.user and return
          end
        end
      else
        redirect_to settings_album_path
      end
    else
      @album = resource
    end
  end

  def settings
    if request.patch? or request.post?
      resource.social = params[:album][:social]
      #@resource.watermark = params[:album][:watermark] #TODO: future feature
      resource.password = params[:album][:social]
      status = resource.status
      resource.status = 'active'
      if resource.valid?
        resource.save
        respond_to do |format|
          if status == 'created'
            format.html { redirect_to resource }
          else
            format.html {redirect_to resource.user}
          end
        end
      end
    end
    @album = resource
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        #TODO: This should probably be :back, but the page won't load correctly due to JS update_view on link click from left side
        format.html { redirect_to @album, notice: 'Album was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.status = 'deleted' #Fake delete
    @album.save

    respond_to do |format|
      format.html { redirect_to @album.user }
      format.json { head :no_content }
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_dynamic_grid.html.erb
<% if @album.photos.blank? %>
      <h3>Sorry, no photos available at this time.</h3>
<% else %>
    <!--<div id='main'>-->
      <ul id='tiles'>
          <% for photo in @album.photos %>
            <li class="image_container item">
                <a href="<%= photo.photo.url %>" class="photo" rel="lightbox" title=<%= photo.file_name %>>
                    <%= image_tag(photo.photo.url(:original), class: 'image') %>
                </a>
                <div class='fave_options animated flipInX'>
                    <%= render partial: 'photos/fave_options', locals: {photo: photo} %>
                </div>
            </li>
          <% end %>
      </ul>
    <!--</div>-->
<% end %>

<!-- Once the page is loaded, initalize the plug-in. -->
<script type="text/javascript">
(function ($){
  // Get a reference to your grid items.
  var handler = $('#tiles li');

  // Init lightbox
  $('a.photo', handler).colorbox({
    rel: 'lightbox'
  });

  // Call the layout function after all images have loaded
  $('#tiles').imagesLoaded(function() {
    handler.wookmark(options);
  });
})(jQuery);
</script>

app/views/albums/_form.html.erb
<script>

</script>

<div class="session_start">
	<%= simple_form_for @album do |f| %>
            <%= f.error_notification %>
	    	<div class="session_start">
				<h4>Where do you want the session to live? Type it below, all one word.</h4>
				<h4>ex. <%= ENV['DISPLAY_SUBDOMAIN'] %>.boomerangproof.com/<%= current_user.name %>/<span id="session_name3">___________________</span></h4>
			</div>
			  <div class="form-inputs big_input">
			  	<%= f.hidden_field :user_id, :value => current_user.id %>
				<%= f.input :name, :label => false %>
			  </div>
			  <br>
			  <%= f.button :submit, "CONTINUE" %>
	<% end %>

	</div>
    <%= render 'layouts/progress_circles', number: 4, active: 1 %>
</div>
<script>
        $("#album_name").trigger('focus');
	    $("#album_name").on("keyup change", function() {
	      var value = $("#album_name").val();
	      $("#session_name").text(value);
	      $("#session_name2").text(value);
	      $("#session_name3").text(value.replace(/\s/g, ''));
	      $("#new_photo").attr('id', 'butts');
	    });
</script>

app/views/albums/_form_scripts.html.erb
<%javascript_tag 'fancyInput.js' %>
<script>
    $('section :input').val('').fancyInput()[0].focus();
</script>
<script>
	jQuery(function(){
	    $("#album_name").on("keyup change", function() {
	      var value = $("#album_name").val();
	      $("#session_name").text(value);
	      $("#session_name2").text(value);
	      $("#session_name3").text(value.replace(/ /g, '_'));
	      $("#new_photo").attr('id', 'butts');
	    });
	});
</script>

app/views/albums/_load_guest.html.erb
<div class='welcome_screen'>
	<div class="welcome_text">

		<h1>WELCOME!</h1>
		<h3>IS THIS YOUR FIRST TIME HERE?<br> WHAT DO YOU WANT US TO CALL YOU?</h3>
		<%= simple_form_for(Guest.new, html: { class: 'super_focus' }) do |f| %>
		  <%= f.error_notification %>

		  <%= f.hidden_field :album_id, :value => @album.id %>
		  <%= f.hidden_field :album_url, :value => request.original_url %>
		  <%= f.hidden_field :last_sign_in_ip, :value => request.remote_ip %>

		  <div class="form-inputs">
		    <%= f.input :name, :label => false, :autofocus => true %>
		  </div>

		    <%= f.button :submit, "CONTINUE" %>
		<% end %>
		<% if @guests.any? %>
            <h2>OR</h2>

            <h3>ARE YOU ONE OF THESE BEAUTIFUL PEOPLE?</h3>
            <% @guests.each do |guest| %>
                <h4 class="beautiful_people"><%= link_to guest.name, start_session_guests_path(:guest => guest.id, :url => request.original_url) %></h4>
            <% end %>
        <% end %>
	</div>
</div>

app/views/albums/_new_grid.html.erb
<div id="grid-gallery" class="grid-gallery">
    <section class="grid-wrap">
        <ul class="grid">
            <li class="grid-sizer"></li>
            <% for photo in @photos %>
              <li class="image_container">
                <figure>
                    <%= image_tag(photo.photo.url(:large), class: 'main_image') %>
                    <a alt='<%=photo.photo_file_name.split('.').first%>' class='fancybox' rel='group' href='<%= photo.photo.url(:original) %>' data-photo-id="fave-<%= photo.id %>">
                      <div class="image_zoom <%= photo.id %>"><%= image_tag('magnifier.png')%></div>
                    </a>
                    <div id="fave-<%= photo.id%>" class='fave_options <%= photo.id %>'>
                      <%= render partial: 'photos/fave_options', locals: {photo: photo} %>
                      <div class="fave_count <%= photo.id %>"><p><%= photo.followers_count %></p></div>
                      <% if (photo.followers_count == 0) %>
                          <script type='text/javascript'>
                              $('.fave_count.<%= photo.id %>').hide();
                          </script>
                      <% end %>
                    </div>
                </figure>
              </li>
            <% end %>
        </ul>
    </section>

 </div>

<%= javascript_include_tag "imagesloaded.pkgd.min.js", "masonry.pkgd.min.js", "classie.js", "cbpGridGallery.js" %>
<script>
    new CBPGridGallery( document.getElementById( 'grid-gallery' ) );
</script>

<!-- Add jQuery library -->
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>

<%= javascript_include_tag "jquery.mousewheel-3.0.6.pack.js", "jquery.fancybox.js", "jquery.fancybox-buttons.js?v=1.0.5", "jquery.fancybox-media.js?v=1.0.6", "jquery.fancybox-thumbs.js?v=1.0.7" %>
<%= stylesheet_link_tag "jquery.fancybox.css", "jquery.fancybox-buttons.css?v=1.0.5", "jquery.fancybox-thumbs.css?v=1.0.7" %>

<script type="text/javascript">
  $(document).ready(function() {
      /* Disable right click */
      $(document).bind("contextmenu",function(e) {
          return false;
      });
      $(".fancybox").fancybox({
          openEffect  : 'fade',
          closeEffect : 'fade',
          padding     : 0,
          margin      : [20, 30, 20, 30], // Increase left/right margin
          beforeLoad: function() {
              //BUGBUG: this should be in beforeShow but v3 is broken for setting title in beforeShow
              this.title = $(this.element).attr('alt');
              if (this.title) {
                  //Bring in the extra data that passes the fave controls
                  var el, id = $(this.element).data('photo-id');
                  if (id) {
                      el = $('#' + id);
                      if (el.length) {
                          this.title += '<span class="lightbox-corner">' + el.html() + '</span>';
                      }
                  }
                  // Add in the social  parts of title
                  <% if @album.social %>
                  this.title += '<span class="social"><span class="info">Share:</span> ';

                  // Add Facebook like button
                  this.title += '<a href="http://www.facebook.com/sharer.php?s=100&p[url]=' + '<%= @album.url %>' + '&p[images][0]=' + this.href + '&p[title]=Proof of recent photoshoot"><%= image_tag('facebook.png') %></a>';
                  //this.title += '<iframe src="//www.facebook.com/plugins/like.php?href=' + this.href + '&amp;layout=button_count&amp;show_faces=true&amp;width=500&amp;action=like&amp;font&amp;colorscheme=light&amp;height=23" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:110px; height:23px;" allowTransparency="true"></iframe>';

                  // Add tweet button
                  this.title += '<a href="https://twitter.com/share" class="twitter-share-button" data-count="none" data-url="' + this.href + '"><%= image_tag('twitter.png') %></a> ';

                  // Pintrest
                  this.title += '<a href="https://pinterest.com/pin/create/bookmarklet/?media=' + this.href + '&url=' + '<%= @album.url %>' + '&is_video=false&description=Proof of recent photoshoot"><%= image_tag("pinterest.png") %></a>';

                  // tumblr
                  //this.title += '<a href="http://www.tumblr.com/share/link?url=' + '<%= @album.url %>' + '&name=' + '<%= @album.title %>' + '&description=Proof of recent photoshoot">TUMBLR</a>';

                  this.title += '</span>';
                  <% end %>
              }
          },
          beforeShow: function () {
              /* Enable fave from click on image */
              $.fancybox.wrap.bind("click", function(e){
                  $.ajax($(this).parent().find('.fave_action')[0].href, {'dataType':'script'})
                          .beforeSend(function(){
                              $($(this).parent().find(".fave_controls")[0]).addClass('hover');
                          })
                          .done(function(){
                              $($(this).parent().find(".fave_controls")[0]).removeClass('hover');
                          });
                  return false;
              });
              /* Disable right click */
              $.fancybox.wrap.bind("contextmenu", function (e) {
                  return false;
              });
          },
          afterShow: function() {
              $(".fancybox-title").wrapInner('<div />').show();
              // Grid view hover effect
              $(".fancybox-inner").mouseover(function(){
                  $($(this).parent().find(".fave_controls")[0]).addClass('hover');
              }).mouseleave(function(){
                          $($(this).parent().find(".fave_controls")[0]).removeClass('hover');
                      });
          },
          helpers : {
              title : {
                  type: 'outside'
              },
              overlay : {
                  css : {
                      'background' : 'rgba(0, 0, 0, 0.8)'
                  }
              }
          }
      });
  });
</script>

app/views/albums/display.html.erb
<%= render 'new_grid' %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/new.html.erb
<div class="session_start">
  <%= image_tag('upload_cloud.png') %>
  <h1>NEW SESSION</h1>
</div>

<% if current_user.admin? %>
    <%= render 'form' %>
<%elsif current_user.active?%>
    <%# render('silver_form') %>
    <%= render 'form' %>
<% end %>

app/views/albums/not_authorized.html.erb
<div class="session_start">
    <h1>UNAUTHORIZED</h1>
</div>
<div class="session_start">
    <h4>
      The password provided was incorrect.
      <%= link_to "Try again here", request.url %>
    </h4>
</div>

app/views/albums/set_password.html.erb
<div class="session_start">
    <% if @album.status == 'created' %>
      <%= image_tag('upload_cloud.png') %>
      <h1>NEW SESSION</h1>
    <% else %>
      <h1>SET PASSWORD</h1>
    <% end %>
</div>
<p class='session_start'>
  Perfect. Now, if you would like to password protect this session, flip the toggle to 'ON' and type in a password.
  If not, just click CONTINUE.
</p>
<div class="session_start">
	<%= simple_form_for @album, url: 'set_password' do |f| %>
            <%= f.error_notification %>
			  <div class="form-inputs">
				<div class="make-switch">
                    <%= f.check_box :password_toggle %>
                </div>
                <br/>
                <br/>
                <% if @album.password %>
                    Current Password:
                    <%= @album.password %>
                <% end %>
                <br/>
                <br/>
                <% holder = @album.password ? 'CHANGE PASSWORD' : 'CREATE PASSWORD' %>
                <%= f.input :password, :placeholder => holder, label: false %>
			  </div>
			  <br>
			  <%= f.button :submit, "CONTINUE" %>
	<% end %>

	</div>
</div>
<%# javascript_include_tag 'fancyInput' %>
<% if @album.status == 'created' %>
    <%= render 'layouts/progress_circles', number: 4, active: 3 %>
<% end %>

app/views/albums/set_title.html.erb
<div class="session_start">
      <% if @album.status == 'created' %>
      <%= image_tag('upload_cloud.png') %>
      <h1>NEW SESSION</h1>
    <% else %>
      <h1>CHANGE TITLE</h1>
    <% end %>
</div>
<div class="session_start">
	<%= simple_form_for @album, url: 'set_title' do |f| %>
            <%= f.error_notification %>
	    	<div class="session_start">
				<h4>What would you like to call this session?</h4>
			</div>
			  <div class="form-inputs big_input">
				<%= f.input :title, :label => false %>
			  </div>
			  <br>
			  <%= f.button :submit, "CONTINUE" %>
	<% end %>

	</div>
	<%= javascript_include_tag 'fancyInput' %>
    <% if @album.status == 'created' %>
        <%= render 'layouts/progress_circles', number: 4, active: 2 %>
    <% end %>
</div>
<script>
      $("#album_title").trigger('focus');
</script>

app/views/albums/settings.html.erb
<div class="session_start">
  <% if @album.status == 'created' %>
      <%= image_tag('upload_cloud.png') %>
      <h1>NEW SESSION</h1>
  <% else %>
    <h1>SETTINGS</h1>
  <% end %>
</div>
<div class="session_start">
	<%= simple_form_for @album, url: 'settings' do |f| %>
            <%= f.error_notification %>
	    	<div class="session_start">
				<h4>Please specify album settings</h4>
			</div>
			  <div class="form-inputs">
			  	<div class="options_box">
					<!--<h3>-->
						<!--WATERMARK:-->
					    <!--<div class="make-switch">-->
		    				<!--<%= f.check_box :watermark %>-->
						<!--</div>-->
					<!--</h3>-->
					<h3>
						SOCIAL SHARE:
						<div class="make-switch">
		    				<%= f.check_box :social %>
						</div>
					</h3>
				</div>
			  </div>
			  <br>
			  <%= f.button :submit, "CONTINUE" %>
	<% end %>
	</div>
    <% if @album.status == 'created' %>
      <%= render 'layouts/progress_circles', number: 4, active: 4 %>
    <% end %>
</div>

app/views/albums/show.html.erb
<div class="session_start">
  <%= image_tag('upload_cloud.png') %>
  <h1>UPLOAD PHOTOS</h1>
  <h4>Found at: <a href="<%= @album.url %>"><%= @album.url %></a></h4>
  <br>
  <div>
    Boomerang does not currently offer an in-app watermarking function. We'd
    like to leave this feature up to the photographer (for now) to ensure that
    photos are marked to their liking pre-upload. Also, we've set a limit of
    10mb per file upload to help us keep image quality high and fast for
    anyone viewing your work. Thanks!
  </div>
  <br>
  <br>
  <div class="complete">
    <%= link_to "Upload Complete!", user_path(@album.user) %>
  </div>
  <%= form_for(Photo.new, html: { multipart: true, class: 'dropzone'}) do |f|  %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :album_id, :value => @album.id %>
    <div class="fallback">
        <%= f.file_field :photo %><br>
        <%= f.submit "Upload" %>
    </div>
  <% end %>
</div>

<script>
    // disable auto discover
    Dropzone.autoDiscover = false;
    // grap our upload form by its id
    $("#new_photo").dropzone({
        // restrict image size to a maximum 10MB
        maxFilesize: 10,
        // changed the passed param to one accepted by
        // our rails app
        paramName: "photo[photo]",
        // show remove links on each image upload
        addRemoveLinks: true,
        // if the upload was successful

        init: function () {
            <% @album.photos.each do |photo| %>
                var id = <%= photo.id %>
                var file = { name: "<%= photo.photo_file_name %>", size: <%= photo.photo_file_size || 0 %>, type: "<%= photo.photo_content_type %>" };
                this.options.addedfile.call(this, file);
                this.options.thumbnail.call(this, file, "<%= photo.photo.url(:thumb) %>");
                $(file.previewTemplate).find('.dz-remove').attr('id', id);
            <% end %>
            this.on("complete", function (file) {
                if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
                    $(".complete").show();
                }
            });
        },

        success: function(file, response){
            // find the remove button link of the uploaded file and give it an id
            // based of the fileID response from the server
            $(file.previewTemplate).find('.dz-remove').attr('id', response.fileID);
            // add the dz-success class (the green tick sign)
            $(file.previewElement).addClass("dz-success");
        },
        //when the remove button is clicked
        removedfile: function(file){
            // grap the id of the uploaded file we set earlier
            var id = $(file.previewTemplate).find('.dz-remove').attr('id');
            if(id == null){
                $(file.previewElement).addClass('hidden');
            }else{
                // make a DELETE ajax request to delete the file
                $.ajax({
                    type: 'DELETE',
                    url: '/photos/' + id,
                    success: function(data){
                        console.log(data.message);
                        $(file.previewElement).addClass('hidden');
                    }
                });
            };
        }
    });
</script>

app/views/albums/sign_in.html.erb
<div class="session_start">
      <h1>PASSWORD REQUIRED</h1>
</div>
<div class="session_start">
  <%= simple_form_for :album, url: request.url do |f| %>
  <div class="form-inputs">
    <%= f.input :password, :placeholder => "PASSWORD", label: false %>
  </div>
  <br>
  <%= f.button :submit, "CONTINUE" %>
  <% end %>
</div>
<%= javascript_include_tag 'fancyInput' %>
<script>
    $('section :input').val('').fancyInput()[0].focus();
    $("#password").trigger('focus');
</script>