config/routes.rb
BMRNG::Application.routes.draw do

  get '/blog', to: redirect("http://google.com")

  resources :answers

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :questions

  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
    put 'update', :to => 'registrations#update'
    get 'account', :to => 'registrations#edit'
  end

  resources :users do
    resources :subscriptions
    match :send_feedback, via: [:get, :post]
    match :request_support, via: [:get, :post]
    member do
      get :analytics
      get :manage
      get :update_view
      match :change, via: [:get, :post, :patch]
      match :welcome, via: [:get]
      match :set_human_name, via: [:patch, :post]
      match :set_studio, via: [:get, :post]
      match :set_studio_url, via: [:get, :post]
      match :set_url, via: [:get, :post]
      match :set_logo, via: [:get, :post]
      match :set_questions, via: [:get, :post]
      match :welcome_complete, via: [:get]
      match :edit_subscription, via: [:get]
    end
  end

  resources :guests do
    collection do
      get :destroy_session
      get :start_session
      get :load
      get :save
      match :ask_questions, via: [:get, :post]
      get :thank_you
    end
  end

  resources :albums do
    member do
      match :display, via: [:get, :post]
      match :set_title, via: [:get, :post, :patch]
      match :set_password, via: [:get, :patch]
      match :settings, via: [:get, :post, :patch]
    end
    resources :photos do
      member do
        get :display
      end
    end
  end
    
  resources :photos do
    member do
      get :fave
      get :defave
    end
  end

  mount StripeEvent::Engine => '/stripe'

  get "home/update_view"

  get "photos/update_view"

  get "/feedback", to: 'questions#index'

  get '/admin/become' => 'admin#become'

  #constraints DomainConstraint.new ['myalbumviewer.dev', 'myalbumviewer.com'] do
  #  root to: 'home#viewer', as: :viewer
  #  resources :users, path: '/' do
  #    get '/:album_id' => 'albums#display'
  #  end
  #end

  constraints SubdomainConstraint.new ['cp'] do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  constraints SubdomainConstraint.new ['www'] do
    root to: 'home#index', as: :home
    resources :users, path: '/' do
      match '/:album_id' => 'albums#display', via: [:get, :post]
    end
  end

  root to: 'home#index', as: :default
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  acts_as_followable
  include Rails.application.routes.url_helpers

## ========================== ATTRIBUTES ACCESSIBLE ============================

  attr_accessible :album_id, :photo, :user_id, :photo_file_name, 
                  :photo_content_type, :photo_file_size

## ================================ RELATIONS ==================================

  belongs_to :album
  belongs_to :user

##================================= SCOPES =====================================

  default_scope include: :followings

## ================================= IMAGES ====================================

  has_attached_file :photo,
    :styles => {
      :original => ['1200x1200>', :jpg],
      :thumb   => ['100x100>',    :jpg],
      :large => ['400x400>', :jpg],
    },
    :convert_options => { :all => '-background white -flatten +matte',
                          :thumb => '-strip',
                          :large => '-strip'},
    :default_url => "/images/missing.png"
  validates_attachment_content_type :photo, :content_type => ["image/jpg",
                                                              "image/jpeg",
                                                              "image/png",
                                                              "image/gif"]
  validates_attachment_file_name :photo, :matches => [/png\Z/,
                                                      /jpe?g\Z/,
                                                      /gif\Z/]

  def to_jq_upload
    {
      "name" => read_attribute(:photo_file_name),
      "size" => read_attribute(:photo_file_size),
      "url" => photo.url(:original),
      "delete_url" => photo_path(self),
      "delete_type" => "DELETE"
    }
  end

  # Just remove the extention for displaying in UI
  def file_name
    photo_file_name.split('.')[0..-2].join('.') rescue nil
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  def display
    @photo = Photo.find_by_id(params[:id])
    @album = @photo.album
  end

  def fave
    @photo = Photo.find(params[:id])
    album = Album.find_by(id: @photo.album.id)
    current_guest.follow(@photo)

    respond_to do |format|
      format.html { redirect_to display_album_path(id: album.id) }
      format.js { render 'defave' }
    end
  end

  def defave
    @photo = Photo.find(params[:id])
    current_guest.stop_following(@photo)
    
    respond_to do |format|
      format.html { redirect_to display_album_path(id: @photo.album.id) }
      format.js { render 'fave'}
    end
  end

  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
  	@photo = Photo.new(params[:photo])
    #@photo.photo = params[:file]
  	if @photo.save
      respond_to do |format|
        format.json {render json: { message: "success", fileID: @photo.id }, :status => 200}
        format.html {redirect_to @photo.album}
      end

  	else
  	  #  you need to send an error header, otherwise Dropzone
      #  will not interpret the response as an error:
  	  render json: { error: @photo.errors.full_messages.join(',')}, :status => 400
  	end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      render json: { message: "File deleted from server" }
    else
      render json: { message: @photo.errors.full_messages.join(',') }
    end
  end
  #def destroy
  #  @photo = Photo.find(params[:id])
  #  @photo.destroy
  #
  #  respond_to do |format|
  #    format.html { redirect_to photos_url }
  #    format.json { head :no_content }
  #  end
  #end

  private
  def upload_params
  	params.require(:photo).permit(:photo, :file)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_defave.html.erb
<% photo ||= @photo %>
<span class="fave_corner">
<%= link_to defave_photo_path(:id => photo.id), :remote => true, class: 'fave_action' do %>
    <%= image_tag('corner.png') %>
<% end %>
</span>
<script>
  //$('.fave_options.<%= photo.id%>').removeClass("animated flipInX");
  $('.fave_controls.<%= photo.id%>').addClass("visible");
  $('.image_zoom.<%= photo.id%>').addClass("visible");
 // $('.fave_options.<%= photo.id%>').show();
  //$('.fave_options.<%= photo.id%>').attr('style', 'display:block');
  $('.fave_count.<%= photo.id %>').html('<p><%= photo.followers_count %></p>');
  $('.fave_count.<%= photo.id %>').attr('style', '');
</script>

app/views/photos/_fave.html.erb
<% photo ||= @photo %>
<span class="fave_corner">
<%= link_to fave_photo_path(:id => photo.id), :remote => true, class: 'fave_action' do %>
	<%# image_tag('heart.png', :class => "small-heart") %>
    <%= image_tag('corner.png') %>
<% end %>
</span>
<script>
  //$('.fave_options.<%= photo.id %>').addClass("animated flipInX");
  $('.fave_controls.<%= photo.id %>').removeClass("visible");
  $('.image_zoom.<%= photo.id %>').removeClass("visible");
  //$('.fave_options.<%= photo.id %>').attr('style', '');
  <% if photo.followers_count == 0 %>
      $('.fave_count.<%= photo.id %>').hide();
  <% end %>
</script>

app/views/photos/_fave_options.html.erb
<% faves ||= true if faves.nil? %>
<% if current_guest and faves %>
    <div class="fave_controls <%= photo.id %>">
      <% if current_guest %>
        <% if current_guest.following?(photo) %>
            <%= render 'photos/defave', :photo => photo %>
        <% else %>
            <%= render 'photos/fave', :photo => photo %>
        <% end %>
      <% end %>
    </div>
<% end %>

app/views/photos/_form.html.erb
<%= simple_form_for(@photo) do |f| %>
  <%= f.error_notification %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/photos/defave.js.erb
$('.fave_controls.<%= @photo.id %>').html("<%= escape_javascript(render('defave')).html_safe %>");
$('.fave_count.<%= @photo.id %> p').html("<%= @photo.followers_count %> ")

app/views/photos/display.html.erb
<center>
    <%= image_tag(@photo.photo.url(:large))%>
</center>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/fave.js.erb
$('.fave_controls.<%= @photo.id %>').html("<%= escape_javascript(render('fave')).html_safe %>");
$('.fave_count.<%= @photo.id %> p').html("<%= @photo.followers_count %> ");

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Preview</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= image_tag photo.photo.url %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= image_tag @photo.session_image.url %>
  <h1><%= @photo.album_id %></h1>
  <h1><%= @photo.session_image.content_type %></h1>
</p>


<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/photos/update_view.js.erb
$(".session_name").html("<%= escape_javascript  
	if current_guest.follower_of?(photo)
		render 'photos/defave', :photo => Photo.find_by(id: photo.id)
	else
		render 'photos/fave', :photo => Photo.find_by(id: photo.id)
	end
%>");