config/routes.rb
BMRNG::Application.routes.draw do

  get '/blog', to: redirect("http://google.com")

  resources :answers

  #mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :questions

  devise_for :users, :controllers => { :registrations => 'registrations' }

  devise_scope :user do
    put 'update_plan', :to => 'registrations#update_plan'
    put 'update_card', :to => 'registrations#update_card'
    put 'update', :to => 'registrations#update'
    get 'account', :to => 'registrations#edit'
  end

  resources :users do
    resources :subscriptions
    match :send_feedback, via: [:get, :post]
    match :request_support, via: [:get, :post]
    member do
      get :analytics
      get :manage
      get :update_view
      match :change, via: [:get, :post, :patch]
      match :welcome, via: [:get]
      match :set_human_name, via: [:patch, :post]
      match :set_studio, via: [:get, :post]
      match :set_studio_url, via: [:get, :post]
      match :set_url, via: [:get, :post]
      match :set_logo, via: [:get, :post]
      match :set_questions, via: [:get, :post]
      match :welcome_complete, via: [:get]
      match :edit_subscription, via: [:get]
    end
  end

  resources :guests do
    collection do
      get :destroy_session
      get :start_session
      get :load
      get :save
      match :ask_questions, via: [:get, :post]
      get :thank_you
    end
  end

  resources :albums do
    member do
      match :display, via: [:get, :post]
      match :set_title, via: [:get, :post, :patch]
      match :set_password, via: [:get, :patch]
      match :settings, via: [:get, :post, :patch]
    end
    resources :photos do
      member do
        get :display
      end
    end
  end
    
  resources :photos do
    member do
      get :fave
      get :defave
    end
  end

  mount StripeEvent::Engine => '/stripe'

  get "home/update_view"

  get "photos/update_view"

  get "/feedback", to: 'questions#index'

  get '/admin/become' => 'admin#become'

  #constraints DomainConstraint.new ['myalbumviewer.dev', 'myalbumviewer.com'] do
  #  root to: 'home#viewer', as: :viewer
  #  resources :users, path: '/' do
  #    get '/:album_id' => 'albums#display'
  #  end
  #end

  constraints SubdomainConstraint.new ['cp'] do
    devise_scope :user do
      root to: "devise/sessions#new"
    end
  end

  constraints SubdomainConstraint.new ['www'] do
    root to: 'home#index', as: :home
    resources :users, path: '/' do
      match '/:album_id' => 'albums#display', via: [:get, :post]
    end
  end

  root to: 'home#index', as: :default
end

app/views/layouts/_display_nav.html.erb
<% if @album.user and @album.user.logo %>
<%= link_to image_tag(@album.user.logo.url(:thumb), class: 'nav_img'), @album.user.link, :target => "blank"%>
<%end %>
<span class="album_title">
  <%= @album.title %>
</span>

<span class="pull-right">
  <span class="faves_saves">
    <span class='heart'>
      <% if params[:faves] == "true" %>
        <%= link_to(image_tag('heart.png', width: 20) + " all", url_for())%>
      <% else %>
        <%= link_to(image_tag('red_heart.png', width: 20) + " fave", url_for(faves: true)) %>
      <% end %>
    </span>
      <%= link_to image_tag('cloud.png', width: 25) + " save", save_guests_path(album_id: @album.id) %>
  </span>
</span>

app/views/layouts/_home_navigation.html.erb
<a data-target=".nav-collapse" data-toggle="collapse" class="btn-navbar" href="##">
    <!--These are to make the button look fancy-->
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<div class="nav-collapse pull-right">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <%= link_to 'Watch', '#watch', class: 'scroll-link', :"data-id" => 'watch' %>
      </li>
      <li>
        <%= link_to 'Why?', '#why', class: 'scroll-link', :"data-id" => 'why'%>
      </li>
      <li>
        <%= link_to 'How?', '#how', class: 'scroll-link', :"data-id" => 'how'%>
      </li>
      <li>
        <%= link_to 'Price', '#plans', class: 'scroll-link', :"data-id" => 'plans' %>
      </li>
      <li>
        <%= link_to 'Blog', '/blog' %>
      </li>
      <li class="nav_button_top">
        <%= link_to 'Sign In', new_user_session_path %>
      </li>
    </ul>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modals.html.erb
<div class="modal fade" id="logo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">LOGO</h4>
      </div>
      <div class="modal-body">

      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="link" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">LINK</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for current_user, :url => update_path do |f| %>
          <%= f.input :link, :label => false %>
          <%= f.button :submit, 'UPDATE', :class => 'btn-primary big_button' %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="password" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"  style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">PASSWORD</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for(current_user, :as => current_user, :url => registration_path(current_user), :html => { :method => :put, :class => 'form-vertical' }) do |f| %>
          <%= f.error_notification %>
          <%= display_base_errors current_user %>
          <h4>PASSWORD</h4>
          <%= f.input :password, :autocomplete => "off", :hint => "leave it blank if you don't want to change it", :required => false, :label => false %>
          <h4>PASSWORD CONFIRMATION</h4>
          <%= f.input :password_confirmation, :required => false, :label => false %>
          <h4>CURRENT PASSWORD (REQUIRED)</h4>
          <%= f.input :current_password, :hint => "we need your current password to confirm your changes", :required => true, :label => false %>
          <%= f.button :submit, 'UPDATE', :class => 'btn-primary big_button' %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div id="credit_card" class="modal fade" style="display: none;">
  <%= simple_form_for resource, :as => resource_name, :url => update_card_path, :html => {:method => :put, :class => 'form-horizontal card_form' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Credit Card</h3>
    </div>
    <div class="modal-body">
      <div class="field">
        <%= label_tag :card_number, "Credit Card Number" %>
        <%= text_field_tag :card_number, nil, name: nil %>
      </div>
      <div class="field">
        <%= label_tag :card_code, "Card Security Code (CVV)" %>
        <%= text_field_tag :card_code, nil, name: nil %>
      </div>
      <div class="field">
        <%= label_tag :card_month, "Card Expiration" %>
        <%= select_month nil, {add_month_numbers: true}, {name: nil, id: "card_month"}%>
        <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, {name: nil, id: "card_year"}%>
      </div>
      <%= f.hidden_field :name %>
      <%= f.hidden_field :email %>
      <%= f.hidden_field :stripe_token %>
    </div>
    <div style="margin-left: 15px;">
      <%= f.submit "UPDATE", :class => "btn btn-primary big_button" %>
    </div>
  <% end %>
</div>

<div class="modal fade" id="feedback" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"  style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">FEEDBACK</h4>
      </div>
      <div class="modal-body">
        <h2>Ask your clients a few questions</h2>

        <div class="questions_box"></div>

        <br />

        <%= simple_form_for(Question.new, :remote => true) do |f| %>
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.input :content, :label => false %>
          </div>

            <%= f.button :submit, "ASK", :class => "big_button" %>
        <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="support" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"  style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">SUPPORT</h4>
      </div>
      <div class="modal-body">
        <h4>Have an issue? Let us know.</h4>

        <form>
          <textarea></textarea>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="suggestions" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"  style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">SUGGESTIONS</h4>
      </div>
      <div class="modal-body">
        <h2>Have any feature requests? Let us know.</h2>

        <form>
          <textarea></textarea>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<% if current_guest and @album and @album.user%>
    <div class="modal fade" id="save" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">QUESTIONS</h4>
          </div>
          <div class="modal-body">
            <%= simple_form_for(Answer.new) do |f| %>
              <%= f.error_notification %>

              <% @album.user.questions.each do |question| %>
                <%= question.content %>
                <%= f.input :content, :label => false %>
                <%= f.hidden_field :question_id, :value => question.id %>
                <% if current_guest %>
                    <%= f.hidden_field :guest_id, :value => current_guest.id %>
                <% end %>
              <% end %>

                <%= f.button :submit, "SUBMIT" %>
            <% end %>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
<% end %>

<script>
	jQuery(function(){
	    $("#user_name").on("keyup change", function() {
	      var value = $("#user_name").val();
	      $("#session_name3").text(value.replace(' ', '_'));
	    });
	});
</script>

app/views/layouts/_navigation.html.erb
    <div class="container">

      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn-navbar" data-toggle="collapse" data-target=".nav-collapse" href="#">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <!-- Be sure to leave the brand out there if you want it shown -->
      <span class="brand">
        <% if current_user.logo.url.include? 'missing' %>
            <%= link_to 'Managing: ' + current_user.studio_name %>
        <% else %>
            <%= image_tag(current_user.logo.url(:thumb)) unless current_user.logo.url.include? 'missing' %>
        <% end %>
      </span>

      <div class="nav-collapse collapse pull-right">
        <ul class="nav navbar-nav navbar-right">
            <li class="nav_link_top">
                <%= link_to 'SESSIONS', user_path(current_user) %>
            </li>
            <li class="nav_link_top">
                <%= link_to 'ANALYTICS', analytics_user_path(current_user) %>
            </li>

            <li class='dropdown nav_link_top'>
                <a class='dropdown-toggle' data-toggle="dropdown" href="#">INFO</a>
                <!--<b class="caret"></b>-->
                <ul class="dropdown-menu">
                    <li><%= link_to 'LOGO', change_user_path(current_user, what: 'logo') %></li>
                    <li><%= link_to 'LINK', set_studio_url_user_path(current_user) %></li>
                    <!--<li><a data-toggle="modal" href="#link">LINK</a></li>-->
                    <li><%= link_to 'PASSWORD', change_user_path(current_user, what: 'password') %></li>
                    <li><%= link_to 'FEEDBACK', set_questions_user_path(current_user) %></li>
                    <li><%= link_to 'SUBSCRIPTION', change_user_path(current_user, what: 'subscription') %></li>
                    <li><%= link_to 'LOGOUT', destroy_user_session_path, method: :delete %></li>
                </ul>
            </li>
            <li class="nav_link_top red plus_btn">
                <%= link_to '+', new_album_path %>
            </li>
        </ul>
      </div>
    </div>

app/views/layouts/_navigation_bottom.html.erb
    <div class="container">

      <!-- Be sure to leave the brand out there if you want it shown -->
      <span class="brand">
        BOOMERANG | DASHBOARD
      </span>
      <!--<li class="nav"><span class="badge red">5</span></li>-->

      <ul class="nav pull-right">
      <li class="nav_link_bot dark pull-right"><%= link_to "SUPPORT", user_request_support_path(current_user) %></li>
        <li class="nav_link_bot dark pull-right"><%= link_to 'SUGGEST', user_send_feedback_path(current_user) %></li>
      </ul>

    </div>

app/views/layouts/_progress_circles.html.erb
<div class='row'>
    <div class="circle-container">
        <% for count in 1..number %>
            <div class="circle <% if active == count %>active<% else %>non-active<% end %>"></div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "BOOMERANG" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "BOOMERANG" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%# javascript_include_tag "jquery", "bootstrap.min", "scroller.js", "modernizer.custom" %>
    <%# TODO: Should not need fancyInput, but wasn't looking in asset pipeline %>
    <%= javascript_include_tag "fancyInput" %>
    <%= csrf_meta_tags %>
    <% unless Rails.env.development? %>
        <!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("d42af47f3666a837c2caef0a7b74feaf");</script><!-- end Mixpanel -->
    <% end %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-inverse animated fadeInDownBig no-print">
      <nav class="navbar-inner">
        <% if current_user and current_user.active? %>
            <%= render 'layouts/navigation' %>
        <% elsif controller_name.include? 'home' %>

        <%# else %>
            <li><%# link_to 'LOGOUT', destroy_user_session_path, :method=>'delete' %></li>
        <% end %>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
              <% if user_signed_in? %>
                <%# render 'layouts/modals' %>
              <% end %>
            </div>
          </div>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <% if current_user %>
    <div class="navbar navbar-fixed-bottom navbar-inverse animated fadeInUpBig no-print">
      <nav class="navbar-inner">
          <%= render 'layouts/navigation_bottom' %>
      </nav>
    </div>
    <% end %>
  </body>
</html>

app/views/layouts/display.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
    <% if @album %>
        <title><%= "#{@album.name} by #{@album.user.name}" rescue "BOOMERANG"%></title>
    <% else %>
        <title>Boomerang Proof Album Viewer Portal</title>
    <% end %>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "BOOMERANG" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "cbpGridGallery", "modernizr.custom", "application" %>
    <%= javascript_include_tag "jquery.grid-a-licious.min" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <style>
      body.albums{padding-top: 0px;}
    </style>
  </head>
  <body id='body' class="<%= controller_name %> <%= action_name %>">
    <div id="main" role="main">
        <div class="content">
              <%= render 'layouts/messages' if current_user %>
              <%= yield %>
          </div>
    </div> <!-- end of #main -->
    <div class="navbar navbar-fixed-bottom navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/display_nav' if @album%>
        </div>
      </nav>
    </div>
  </body>
</html>

app/views/layouts/marketing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>BOOMERANG PROOF | YOUR ONLINE PHOTO PROOF HOME</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "BOOMERANG" %>">
    <%= yield(:head) %>
    <%= javascript_include_tag "jquery.grid-a-licious.min" %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "bootstrap.min", "bootstrap-responsive.min" %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>" data-spy="scroll" data-target=".navbar">
    <%# if request.subdomain == ENV['PRIMARY_SUBDOMAIN'] %>
      <div class="navbar navbar-fixed-top fixed animated fadeInDownBig  no-print">
        <nav class="navbar-inner">
          <%= render 'layouts/home_navigation' %>
        </nav>
      </div>
    <%# end %>
    <div id="main" role="main">
        <div class="content">
              <%= yield %>
        </div>
    </div>
  </body>
</html>